### ISSUE TITLE
ERROR: LoadError: KeyError: key nothing not found

### ISSUE THREAD

**Issue by bcjr-hue** [biaslab/ForneyLab.jl#146]
Hi, thanks for this wonderful work! 

Could you please help to check?

To reproduce it, please try the code below:

```
using ForneyLab

g = [1,-1]

# hyperparams for information rates estimation

num_samples = 10


# i.u.d
# FFG
G = FactorGraph()

# declare priors as random variables

x = Vector{Variable}(undef,num_samples)
y = Vector{Variable}(undef,num_samples)
s = Vector{Variable}(undef,num_samples+1)
z = Vector{Variable}(undef,num_samples)



@RV s[1] ~ Bernoulli(1/2)

for k = 1:num_samples # Build model sections
    @RV x[k] ~ Bernoulli(1/2)
    @RV z[k] ~ GaussianMeanVariance(0.0, 1.0)
    
    # Observation model
    @RV y[k]  = g[1]*x[k] + g[2]*s[k]+ z[k]
    # Reset state for next section
    s[k+1] = x[k]


end

q = PosteriorFactorization(G)
algo = messagePassingAlgorithm(y)
```

**Comment by ThijsvdLaar** [comment]
Hi, thanks for trying it out. I'll explain how I would approach this issue. First of all, the error message is indeed quite cryptic, we'll need to improve the information it provides. What ForneyLab is trying to tell you is that it can't find a message that is required for scheduling. Inspecting the graph with

`ForneyLab.draw(G, external_viewer=:default)`

indeed shows that the edges representing your observed variables are not terminated by nodes on both ends. ForneyLab needs to be informed about which variables are observed. This can be done by inserting the statement

`placeholder(y[k], :y, index=k)`

after the line where you declare your `y[k]` variable. This line will terminate the `y[k]` edge with a `Clamp` node, whose value will be populated with the `k`th index of the `data[:y]` dictionary entry upon algorithm execution.

Executing your adjusted code, the next error you'll see is about a missing rule for the `Multiplication` node. Because ForneyLab implements analytic updates, you'll need to specify what you mean by the multiplication of a `PointMass` (Dirac-delta) and a `Bernoulli` distribution. For example, what does it mean when you multiply a Bernoulli-distributed variable by `-1`? The resulting variable will not be Bernoulli distributed, because it's support will be `\in {-1, 0}`. There is nothing wrong with this per-se, but you'll need to implement the update rule; or adjust your model accordingly if this is not what you're after. You can implement your own updates as follows:

```
# Bernoulli times PointMass
# Replace :outbound_type with your outbound message type
# i.e. what do you mean when you multiply a Bernoulli distributed variable by -1?

# Backward rule
@sumProductRule(:node_type     => Multiplication,
                :outbound_type => Message{Bernoulli},
                :inbound_types => (Message{Bernoulli}, Nothing, Message{PointMass}),
                :name          => SPMultiplicationOutBNP)

function ruleSPMultiplicationOutBNP(msg_out::Message{Bernoulli, Univariate},
                                    msg_in1::Nothing,
                                    msg_a::Message{PointMass, Univariate})
    # Your update here
end

# Forward rule
@sumProductRule(:node_type     => Multiplication,
                :outbound_type => Message{Bernoulli},
                :inbound_types => (Nothing, Message{Bernoulli}, Message{PointMass}),
                :name          => SPMultiplicationOutNBP)

function ruleSPMultiplicationOutNBP(msg_out::Nothing,
                                    msg_in1::Message{Bernoulli, Univariate},
                                    msg_a::Message{PointMass, Univariate})
    # Your update here
end
```

A similar question holds for addition of two `Bernoulli` random variables, and the addition of a `Bernoulli` and a `Gaussian` random variable.

I hope this gives you a push in the right direction, let me know how it goes.
