### ISSUE TITLE
Use PDMats.jl to work with positive-definite matrices

### ISSUE THREAD

**Issue by marcocox** [biaslab/ForneyLab.jl#30]
The current version is not very robust w.r.t. numerically unstable matrix operations (mainly inverse and Cholesky decomposition). Matrices that theoretically should be positive definite (i.e. covariance matrices) sometimes aren't due to numerical precision errors, which can crash inference algorithms.

A clean and concise way to address this would be to explicitly represent PD matrices by special types, for example based on [PDMats.jl](https://github.com/JuliaStats/PDMats.jl). The types in PDMats.jl explicitly track the Cholesky factor of the PD matrix at hand, and all kinds of matrix operations are overloaded to leverage that. In theory, this should eliminate exceptions related to inverting PD matrices.

**Comment by mroavi** [comment]
I believe this program reproduces this problem. I extended the linear regression example from AIP-5SSB0 for M-dimensional polynomials. If I run the program with N=9 data points and M = 4 the program works fine. If I increase the number of data point to N=10 then I get the following error:
```julia
mean(𝒩(xi=[-15.65, -1.84e+02, -1.10e+03, -5.82e+03, -3.01e+04], w=[[1.51e+02, 4.71e+02, 2.08e+03, 1.03e+04, 5.46e+04][4.71e+02, 2.08e+03, 1.03e+04, 5.46e+04, 3.01e+05][2.08e+03, 1.03e+04, 5.46e+04, 3.01e+05, 1.70e+06][1.03e+04, 5.46e+04, 3.01e+05, 1.70e+06, 9.80e+06][5.46e+04, 3.01e+05, 1.70e+06, 9.80e+06, 5.73e+07]])
) is undefined because the distribution is improper.
error(::String) at error.jl:33
mean(::ProbabilityDistribution{Multivariate,GaussianWeightedMeanPrecision}) at probability_distribution.jl:38
top-level scope at none:0
```
@marcocox Could you double check that indeed this error is due to this issue?

[bayesian-linear-regression.jl.txt](https://github.com/biaslab/ForneyLab.jl/files/2906194/bayesian-linear-regression.jl.txt)
(remove the .txt extension)

**Comment by wmkouw** [comment]
To do list for PDMats implementation
- [ ] get rid of cholinv.
- [ ] write tests for change cholinv -> inv
    - [ ] in helpers.jl
    - [ ] in probability_distribution.jl
    - [ ] in factor_nodes/*.jl
    - [ ] in engines/julia/update_rules/*.jl
- [ ] throw meaningful error when PD is lost after multiplication with PDMats object.
- [ ] insert regularization with 1e-8 to avoid loss of PD due to numerical precision.

This ties to issue in private repo where we want to get rid of unsafeMean and unsafeCov. If we manage to set up something that ensures that all Covariance matrices remain PD, then all unsafeCov's will be regular cov's.

**Comment by wmkouw** [comment]
Note that PDMats doesn't actually fix numerical precision errors. It's just a data type containing the array along with its Cholesky decomposition. It still throws an error if you try to perform an operation on the matrix causing it to be non-PD.

We would still need to do something to counteract the loss of PD due to numerical precision errors. I'm thinking of catching the error (saying that it's no longer PD) and adding 1e-8 to the diagonal of the matrix. If it *is* PD afterwards, then we know that the loss of PD was due to numerical precision and we ignore the error. If it's still *not* PD, then that would be because of an invalid operation and let the error proceed.

**Comment by bertdv** [comment]
There are also improved update rules for (square-root) Gaussian message passing, see the tables in 

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7852382

and 

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7888168

**Comment by wmkouw** [comment]
Interesting approaches. We should discuss the use of these square-root versions in the next meeting.

Going back to the current work on PDMats: Ismail and I are changing all matrices that are required to be Positive-Definite to appropriate PDMats objects. Following that, we need to make sure that all operations where such a matrix is extracted and manipulated (e.g. ProbabilityDistribution.params[:w]) know what to do with PDMats type objects. 

One quick question at the moment: when testing equality for a probability distribution with a PDMats object matrix and one without a PDMats object matrix, should the result be equal or false? For example:
```
ProbabilityDistribution(Multivariate, GaussianMeanPrecision, m=zeros(2), w=ScalMat(2, tiny)) == ProbabilityDistribution(Multivariate, GaussianMeanPrecision, m=zeros(2), w=tiny*eye(2))
```

If we only care whether the values of the parameters are equal, we should let it evaluate to `true`. But if we care about whether they are technically equal (or are equal objects), then we should evaluate it to `false`. Thoughts? Anyone know if this has consequences in parts of ForneyLab?

**Comment by wmkouw** [comment]
Status update:
We are thinking that it is inefficient to switch to PDMats. The problem is that whenever you perform certain algebraic operations on the PDMats object, it loses PD-ness (e.g. Matrix * PDMat = Matrix). If you need the object to be PD later on (e.g. when updating a factor), it will have to be cast to a PDMats type again. Every time you cast to a PDMats type, it performs a Cholesky decomposition. This could happen multiple times in a single time-step.

Also, as noted before, PDMats does not fix numerical precision errors (which was the reason to use it in the first place). We should consider dropping this conversion.

I made an alternative solution. It's in the branch 'inv-num-precision' on the private repo. Cholinv now checks for PD-ness, and if it fails, it will check for PD-ness again after regularizing (adding 1e-8*I). If it passes, it will perform cholinv with the regularization. If it fails, it will rethrow the exception.
```
function cholinv(M::AbstractMatrix)
    """
    Inverts matrix using Cholesky decomposition.

    Catches Positive-Definiteness error, regularizes the matrix with 1e-8 and re-attempts
    Cholesky decomposition. If PosDefException disappears, we know that it was due to
    numerical precision errors. In that case, the function should proceed without throwing
    PosDefException. If PosDefException does not disappear, then it was justified.
    """
    if isposdef(M)
        return inv(cholesky(M))
    else
        try
            return inv(cholesky(M + 1e-8*Matrix(I, size(M))))
        catch exception
            if exception == PosDefException
                throw("PosDefException: Matrix is not positive-definite, even after regularization")
            else
                rethrow(exception)
            end
        end
    end
end
```

I wrote some additional tests as well.

**Comment by wmkouw** [comment]
We are continuing work on incorporating PDMats into ForneyLab. Only the following factor nodes require PD matrices:
- GaussianMeanVariance
- GaussianMeanPrecision
- GaussianMeanWeightedPrecision
- Wishart

We're going through them now, and making sure that all operations involving parameters of these distributions succeed throughout ForneyLab. 

Note that afterwards, tests such as 'isProper' need to be adjusted. *Improper* distributions, i.e. ones with non-PD matrices, are not allowed to be constructed anymore. FL will throw a "Cholesky factorization failed error".

**Comment by wmkouw** [comment]
Status update: 

We have altered all operations involving positive-definite matrices and ForneyLab passes factor node-specific tests.

As discussed, the next step would be to thoroughly profile ForneyLab with PDMats vs without PDMats. Progress has halted though, since this has become a low-priority issue.

On a side note: I just discovered that Distributions.jl is using PDMats (maybe others were already aware of this?). Perhaps there is something to be learned from diving into their code.

**Comment by ThijsvdLaar** [comment]
Thanks @wmkouw! Perhaps you could open a PR with your suggested changes, this way they become easier to compare.

**Comment by wmkouw** [comment]
First results of profiling are in. I wrapped the variational smoothing demo into two functions, one for mean-field and the other for structured factorization inference. I called each function 10 times and clocked CPU time.

```
pdmats branch
│ rep │ mean_field │ structured │
│     │ Float64    │ Float64    │
├─────┼────────────┼────────────┤
│ 1   │ 21.3409    │ 24.4855    │
│ 2   │ 23.2911    │ 27.4257    │
│ 3   │ 26.9614    │ 26.375     │
│ 4   │ 26.7794    │ 23.9505    │
│ 5   │ 23.7093    │ 24.0808    │
│ 6   │ 23.629     │ 23.2268    │
│ 7   │ 23.9751    │ 25.1775    │
│ 8   │ 23.6511    │ 25.2227    │
│ 9   │ 25.7166    │ 24.8583    │
│ 10  │ 23.505     │ 23.5126    │
```
vs
```
master branch
│ rep │ mean_field │ structured │
│     │ Float64    │ Float64    │
├─────┼────────────┼────────────┤
│ 1   │ 19.7014    │ 20.4589    │
│ 2   │ 20.4867    │ 20.5491    │
│ 3   │ 20.5115    │ 20.5617    │
│ 4   │ 20.9111    │ 20.1779    │
│ 5   │ 19.9071    │ 20.218     │
│ 6   │ 19.95      │ 20.2337    │
│ 7   │ 20.2259    │ 20.2301    │
│ 8   │ 20.3995    │ 20.3151    │
│ 9   │ 20.0641    │ 20.0806    │
│ 10  │ 20.2808    │ 20.2528    │
```

It seems there is a 20% increase in computation time for mean-field and a 22% increase for structured inference. 

This demo is a good example, because it uses a lot of Gaussian distributions (covariance matrices are now PDMat objects). However, the Gaussians used here are still univariate and Cholesky decompositions are trivial in the univariate case. To really get an idea of how costly the conversion to PDMats objects is, we should run a similar profiling experiment on a setting involving multivariate Gaussians.

**Comment by ThijsvdLaar** [comment]
The performance problem seems to be with computations of the form
```
V[1:d,1:d] - V[1:d,d+1:end] - V[d+1:end, 1:d] + V[d+1:end,d+1:end] + (m[1:d] - m[d+1:end])*(m[1:d] - m[d+1:end])'
```
which occur e.g. in the structured Gaussian updates. The computation requires slicing and subtraction, which doesn't play well with PDMats. The result is PD, but the intermediate results are not.

**Comment by ThijsvdLaar** [comment]
Issue has been dropped, will close.
