### ISSUE TITLE
Replacing ForneyLab methods with native Julia methods if possible

### ISSUE THREAD

**Issue by semihakbayrak** [biaslab/ForneyLab.jl#66]
It is a good practice to stick to native Julia methods as much as possible so that the current inference algorithms in ForneyLab can easily interface with other Julia packages. For example: cholinv method of ForneyLab sometimes prevent the flow of Flux variables through FFG but when it is replaced with inv() method of Julia, the problem disappears.

**Comment by ThijsvdLaar** [comment]
While I agree that it is better to reuse native Julia methods, simply replacing `cholinv` with `inv` is not the preferred solution here. Replacing will lead to a significant performance decrease, because larger matrices can lose PD-ness due to numeric instabilities. A better solution was proposed in #30, where PD matrices are assigned a separate abstraction.

**Comment by ThijsvdLaar** [comment]
Will close in favor of #30
