### ISSUE TITLE
Composite nodes: message passing on subgraphs without custom rules

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ForneyLab.jl#76]
_Problem:_
When a composite node does not have a specified message passing rule, it is desired that this composite node simply gets expanded including its internal schedule. The number of messages initialized in the function `messagePassingAlgorithm()` in `src/engine/julia/message_passing.jl` bases this on the condensed version of the message passing schedule. 
![image](https://user-images.githubusercontent.com/44952318/72729920-9c30e180-3b90-11ea-8670-1fd5d115949b.png)
Therefore the following error occurs when executing the message passing.
```
BoundsError: attempt to access 7-element Array{Message,1} at index [8]
Stacktrace:
 [1] setindex! at .\array.jl:782 [inlined]
 [2] step!(::Dict{Symbol,Real}, ::Dict{Any,Any}, ::Array{Message,1}) at .\none:12
 [3] step! at .\none:5 [inlined] (repeats 2 times)
 [4] top-level scope at .\In[15]:26
```

_Proposed solution_
Moving `n_messages = length(schedule)`  after the second `condense()` call in the function above solves the problem and does not affect the `composite_node.ipynb` demo. I am, however, not sure whether it conflicts with any other part of the code.

**Comment by ThijsvdLaar** [comment]
This issue should be solved after the recent refactoring of the code generation backend; although we still need to include an integration test for this case. I'll leave this issue open for now, until we have a test.

Feel free to submit a pull request when you identify an issue and already know the solution. It's also a nice way to get credit for your idea, because your commit will be included in the code base.
