### ISSUE TITLE
Improve stability when inverting positive definite matrices

### ISSUE THREAD

**Issue by ThijsvdLaar** [biaslab/ForneyLab.jl#86]
The `cholinv` function is used extensively to invert positive definite (mostly covariance/precision) matrices. The idea is that this function assumes that the argument matrix should be positive definite, despite numeric instabilities. If an initial Cholesky decomposition fails, a slight regularization is added to the diagonal, and another attempt is made. However, the regularization is arbitrary, and might not be enough to render the matrix positive definite.

A simple fix might be (after a failed initial Cholesky decomposition) to obtain an eigenvalue decomposition of the matrix, set the negative eigenvalues to `tiny`, and reconstruct the inverse matrix:
```jl
W = [2.0 0.0 0.0; 0.0 0.2 -0.5; 0.0 -0.5 0.2] # A singular precision matrix
(l, Q) = eigen(W) # Deconstruct
k = clamp.(l, tiny, Inf) # Correct for negative eigenvalues
V = Q'*Diagonal(1.0./k)*Q # Inverted reconstruction (positive definite)
```

This approach is rather blunt (and more expensive), because it will render any matrix positive definite without raising an error. In order to resolve this, we might raise a warning if one of the eigenvalues is largely negative.

**Comment by ismailsenoz** [comment]
I have couple of comments for this issue. Firstly lets look at a fairly simple example Ax=b. To solve naively the inversion requires O(n^3). If however you have lots of b vectors to solve then it's better to factorize A (again with complexity O(nˆ3) at the very best O(nˆ2.3)) and store the factorization. Then reuse the factorization to compute the solution which requires O(n^2). Even in this simple scenario factorization speeds up. For example, if we have a clamp covariance matrix that is not changing I think it would be faster to factorize and use the factorization to recompute. So I am totally behind the idea of factorizations. This trick @ThijsvdLaar suggests is fairly known however has some disadvantages. The problem is rooted in the effect of small eigenvalues in the inversion. Consider an observation model with some noise. Then the small eigenvalues often originate from the covariance matrix of the noise process. So if you have an observation around the noise level the proposed ceiling method for eigenvalues has drastic influences in the estimation process. Because you remove the eigenvalues that are potentially noise related you are removing that information. Yes it helps the inversion however it might have  consequences during inference. Another way would be to sort the eigenvalues and consider the laplacian of the eigenvalues. The argmin of the laplacian is the lowest eigenvalue we should replace.  Example code below;

```
#function to calculate 1d laplacian
function ∇²(f)
    ∇²f = zeros(size(f,1))
    ∇²f[1] = f[2]-f[1]
    ∇²f[end] = f[end]-f[end-1]
    for y = 2:size(f,1)-1,
        ∇²f[y] = f[y-1] + f[y+1]  - 2f[y]
    end
    return ∇²f
end
```
The code for inversion. 
```
W = [2.0 0.0 0.0; 0.0 0.2 -0.5; 0.0 -0.5 0.2] # A singular precision matrix
(l, Q) = eigen(W) # Deconstruct
k = clamp.(l, l[argmin(∇²(l))], Inf) # Correct for negative eigenvalues
V = Q'*Diagonal(1.0./k)*Q # Inverted reconstruction (positive definite)
```

**Comment by marcocox** [comment]
Today I was busy investigating and fixing a similar problem in `GaussianProcessLab.jl` (`chol` sometimes throws `PosDefException` even though the matrix should be posdef in theory). I came to the following conclusions which might be useful in this discussion as well:

1. Doing an eigenvalue decomp, making sure all eigen values are positive, and then 'reconstructing' the original matrix from the modified decompositon is insufficient to solve the problem in all cases (though it helps in a lot of cases).
2. The problem is that if the input matrix contains very large values (in the order of `1e30` for `Float64`), modifying the eigen values or adding some additive constant or noise to the diagonal is not guaranteed to have any impact since the modification might not meet the significant precision threshold for the `Float64`. As an example, observe that `3.97605e28 + 1 == 3.97605e28` holds true.
3. I came up with the following workaround to add jitter to the diagonal of the input matrix in a way that all linear dependencies among rows and columns are broken with a high probability, taking the precision of `Float64` into account. This should ensure that all leading principal minors are positive with high probability, which is a necessary and sufficient condition for positive definiteness. Also see [Sylvester's criterion](https://en.wikipedia.org/wiki/Sylvester%27s_criterion). Note that this is Julia 0.6 code.

```jl
function safeChol(A::Hermitian)
    # `safeChol(A)` is a 'safe' version of `chol(A)` in the sense
    # that it adds jitter to the diagonal of `A` and tries again if
    # `chol` raised a `PosDefException`.
    # Matrix `A` can be non-positive-definite in practice even though it
    # shouldn't be in theory due to finite floating point precision.
    # If adding jitter does not help, `PosDefException` will still be raised.
    L = similar(A)
    try
        L = chol(A)
    catch Base.LinAlg.PosDefException
        # Add jitter to diagonal to break linear dependence among rows/columns.
        # The additive noise is input-dependent to make sure that we hit the
        # significant precision of the Float64 values with high probability.
        jitter = Diagonal(1e-13*(rand(size(A,1))) .* diag(A))
        L = chol(A + jitter)
    end
end
```

Probably there are better ways to do this.

**Comment by hrhill** [comment]
GMW81 algorithm calculates a nearest PD matrix, there is an implementation herehttps://github.com/timholy/PositiveFactorizations.jl that might be useful?
